/*eslint-disable*/

export const news = [
    {
        title: "New York Jets-Atlanta Falcons, Miami Dolphins",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum efficitur in lorem in lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Suspendisse arcu purus, sagittis nec tempus eget, dapibus in sapien. Mauris laoreet ipsum nisl. Nulla facilisi. Quisque viverra, risus ut vehicula varius, neque arcu pulvinar felis, et ornare nisi elit at odio. Sed enim quam, auctor et malesuada ut, interdum vitae diam. Fusce facilisis tristique odio nec iaculis. Integer varius nisl eu leo fringilla, in ullamcorper erat accumsan. Donec quis lobortis leo. Nulla in neque ut lorem tempus laoreet vitae sed diam. Ut eu turpis ut ipsum sodales pulvinar et nec enim. Vivamus id lectus commodo, porta nulla id, ullamcorper nulla. Praesent feugiat metus commodo, consequat mauris at, auctor justo. Vivamus in gravida neque. Sed faucibus leo eu dui pretium vestibulum. Duis sodales neque odio. Vivamus et fermentum nisi, et faucibus purus. Praesent sed imperdiet massa, vitae sagittis leo. Nam pharetra ultrices risus at tincidunt. Mauris et leo mollis enim aliquet ultrices. Aenean in viverra mauris, eget eleifend sapien. Fusce a lacus dignissim, dapibus lectus in, efficitur lacus. Suspendisse nisl mauris, laoreet id tortor quis, condimentum ornare lorem. Curabitur sagittis venenatis porta. Morbi volutpat nulla vel massa pretium semper. Phasellus augue neque, laoreet ut dignissim sit amet, tincidunt vel ante. Quisque porttitor ultrices augue et ultricies. Fusce tempus purus diam, nec scelerisque nisl dapibus ac. Sed bibendum gravida euismod. Quisque pretium erat lacus. Integer porta mollis mauris, a elementum turpis rhoncus vel. Aenean consequat ac justo ut tincidunt. In hac habitasse platea dictumst. Phasellus in tempus quam. Duis feugiat, orci in suscipit fringilla, metus massa pellentesque odio, id convallis magna leo nec libero. Morbi blandit dignissim commodo. Duis sed tellus magna. Curabitur non neque quis nunc commodo tincidunt. Nullam neque ligula, mattis sed turpis sit amet, blandit tristique dui. Nulla facilisi. Etiam interdum enim ullamcorper ligula pellentesque luctus. Ut tincidunt elit quis velit convallis, a convallis leo aliquet.",
        image:'https://img.freepik.com/free-vector/breaking-news-concept_23-2148514216.jpg?'
    },
    {
        title: "New York Jets-Atlanta Falcons, Miami Dolphins",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum efficitur in lorem in lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Suspendisse arcu purus, sagittis nec tempus eget, dapibus in sapien. Mauris laoreet ipsum nisl. Nulla facilisi. Quisque viverra, risus ut vehicula varius, neque arcu pulvinar felis, et ornare nisi elit at odio. Sed enim quam, auctor et malesuada ut, interdum vitae diam. Fusce facilisis tristique odio nec iaculis. Integer varius nisl eu leo fringilla, in ullamcorper erat accumsan. Donec quis lobortis leo. Nulla in neque ut lorem tempus laoreet vitae sed diam. Ut eu turpis ut ipsum sodales pulvinar et nec enim. Vivamus id lectus commodo, porta nulla id, ullamcorper nulla. Praesent feugiat metus commodo, consequat mauris at, auctor justo. Vivamus in gravida neque. Sed faucibus leo eu dui pretium vestibulum. Duis sodales neque odio. Vivamus et fermentum nisi, et faucibus purus. Praesent sed imperdiet massa, vitae sagittis leo. Nam pharetra ultrices risus at tincidunt. Mauris et leo mollis enim aliquet ultrices. Aenean in viverra mauris, eget eleifend sapien. Fusce a lacus dignissim, dapibus lectus in, efficitur lacus. Suspendisse nisl mauris, laoreet id tortor quis, condimentum ornare lorem. Curabitur sagittis venenatis porta. Morbi volutpat nulla vel massa pretium semper. Phasellus augue neque, laoreet ut dignissim sit amet, tincidunt vel ante. Quisque porttitor ultrices augue et ultricies. Fusce tempus purus diam, nec scelerisque nisl dapibus ac. Sed bibendum gravida euismod. Quisque pretium erat lacus. Integer porta mollis mauris, a elementum turpis rhoncus vel. Aenean consequat ac justo ut tincidunt. In hac habitasse platea dictumst. Phasellus in tempus quam. Duis feugiat, orci in suscipit fringilla, metus massa pellentesque odio, id convallis magna leo nec libero. Morbi blandit dignissim commodo. Duis sed tellus magna. Curabitur non neque quis nunc commodo tincidunt. Nullam neque ligula, mattis sed turpis sit amet, blandit tristique dui. Nulla facilisi. Etiam interdum enim ullamcorper ligula pellentesque luctus. Ut tincidunt elit quis velit convallis, a convallis leo aliquet.",
        image:'https://img.freepik.com/free-vector/breaking-news-concept_23-2148514216.jpg?'
    },
    {
        title: "New York Jets-Atlanta Falcons, Miami Dolphins",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum efficitur in lorem in lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Suspendisse arcu purus, sagittis nec tempus eget, dapibus in sapien. Mauris laoreet ipsum nisl. Nulla facilisi. Quisque viverra, risus ut vehicula varius, neque arcu pulvinar felis, et ornare nisi elit at odio. Sed enim quam, auctor et malesuada ut, interdum vitae diam. Fusce facilisis tristique odio nec iaculis. Integer varius nisl eu leo fringilla, in ullamcorper erat accumsan. Donec quis lobortis leo. Nulla in neque ut lorem tempus laoreet vitae sed diam. Ut eu turpis ut ipsum sodales pulvinar et nec enim. Vivamus id lectus commodo, porta nulla id, ullamcorper nulla. Praesent feugiat metus commodo, consequat mauris at, auctor justo. Vivamus in gravida neque. Sed faucibus leo eu dui pretium vestibulum. Duis sodales neque odio. Vivamus et fermentum nisi, et faucibus purus. Praesent sed imperdiet massa, vitae sagittis leo. Nam pharetra ultrices risus at tincidunt. Mauris et leo mollis enim aliquet ultrices. Aenean in viverra mauris, eget eleifend sapien. Fusce a lacus dignissim, dapibus lectus in, efficitur lacus. Suspendisse nisl mauris, laoreet id tortor quis, condimentum ornare lorem. Curabitur sagittis venenatis porta. Morbi volutpat nulla vel massa pretium semper. Phasellus augue neque, laoreet ut dignissim sit amet, tincidunt vel ante. Quisque porttitor ultrices augue et ultricies. Fusce tempus purus diam, nec scelerisque nisl dapibus ac. Sed bibendum gravida euismod. Quisque pretium erat lacus. Integer porta mollis mauris, a elementum turpis rhoncus vel. Aenean consequat ac justo ut tincidunt. In hac habitasse platea dictumst. Phasellus in tempus quam. Duis feugiat, orci in suscipit fringilla, metus massa pellentesque odio, id convallis magna leo nec libero. Morbi blandit dignissim commodo. Duis sed tellus magna. Curabitur non neque quis nunc commodo tincidunt. Nullam neque ligula, mattis sed turpis sit amet, blandit tristique dui. Nulla facilisi. Etiam interdum enim ullamcorper ligula pellentesque luctus. Ut tincidunt elit quis velit convallis, a convallis leo aliquet.",
        image:'https://img.freepik.com/free-vector/breaking-news-concept_23-2148514216.jpg?'
    },
    {
        title: "New York Jets-Atlanta Falcons, Miami Dolphins",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum efficitur in lorem in lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Suspendisse arcu purus, sagittis nec tempus eget, dapibus in sapien. Mauris laoreet ipsum nisl. Nulla facilisi. Quisque viverra, risus ut vehicula varius, neque arcu pulvinar felis, et ornare nisi elit at odio. Sed enim quam, auctor et malesuada ut, interdum vitae diam. Fusce facilisis tristique odio nec iaculis. Integer varius nisl eu leo fringilla, in ullamcorper erat accumsan. Donec quis lobortis leo. Nulla in neque ut lorem tempus laoreet vitae sed diam. Ut eu turpis ut ipsum sodales pulvinar et nec enim. Vivamus id lectus commodo, porta nulla id, ullamcorper nulla. Praesent feugiat metus commodo, consequat mauris at, auctor justo. Vivamus in gravida neque. Sed faucibus leo eu dui pretium vestibulum. Duis sodales neque odio. Vivamus et fermentum nisi, et faucibus purus. Praesent sed imperdiet massa, vitae sagittis leo. Nam pharetra ultrices risus at tincidunt. Mauris et leo mollis enim aliquet ultrices. Aenean in viverra mauris, eget eleifend sapien. Fusce a lacus dignissim, dapibus lectus in, efficitur lacus. Suspendisse nisl mauris, laoreet id tortor quis, condimentum ornare lorem. Curabitur sagittis venenatis porta. Morbi volutpat nulla vel massa pretium semper. Phasellus augue neque, laoreet ut dignissim sit amet, tincidunt vel ante. Quisque porttitor ultrices augue et ultricies. Fusce tempus purus diam, nec scelerisque nisl dapibus ac. Sed bibendum gravida euismod. Quisque pretium erat lacus. Integer porta mollis mauris, a elementum turpis rhoncus vel. Aenean consequat ac justo ut tincidunt. In hac habitasse platea dictumst. Phasellus in tempus quam. Duis feugiat, orci in suscipit fringilla, metus massa pellentesque odio, id convallis magna leo nec libero. Morbi blandit dignissim commodo. Duis sed tellus magna. Curabitur non neque quis nunc commodo tincidunt. Nullam neque ligula, mattis sed turpis sit amet, blandit tristique dui. Nulla facilisi. Etiam interdum enim ullamcorper ligula pellentesque luctus. Ut tincidunt elit quis velit convallis, a convallis leo aliquet.",
        image:'https://img.freepik.com/free-vector/breaking-news-concept_23-2148514216.jpg?'
    },
    {
        title: "New York Jets-Atlanta Falcons, Miami Dolphins",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum efficitur in lorem in lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Suspendisse arcu purus, sagittis nec tempus eget, dapibus in sapien. Mauris laoreet ipsum nisl. Nulla facilisi. Quisque viverra, risus ut vehicula varius, neque arcu pulvinar felis, et ornare nisi elit at odio. Sed enim quam, auctor et malesuada ut, interdum vitae diam. Fusce facilisis tristique odio nec iaculis. Integer varius nisl eu leo fringilla, in ullamcorper erat accumsan. Donec quis lobortis leo. Nulla in neque ut lorem tempus laoreet vitae sed diam. Ut eu turpis ut ipsum sodales pulvinar et nec enim. Vivamus id lectus commodo, porta nulla id, ullamcorper nulla. Praesent feugiat metus commodo, consequat mauris at, auctor justo. Vivamus in gravida neque. Sed faucibus leo eu dui pretium vestibulum. Duis sodales neque odio. Vivamus et fermentum nisi, et faucibus purus. Praesent sed imperdiet massa, vitae sagittis leo. Nam pharetra ultrices risus at tincidunt. Mauris et leo mollis enim aliquet ultrices. Aenean in viverra mauris, eget eleifend sapien. Fusce a lacus dignissim, dapibus lectus in, efficitur lacus. Suspendisse nisl mauris, laoreet id tortor quis, condimentum ornare lorem. Curabitur sagittis venenatis porta. Morbi volutpat nulla vel massa pretium semper. Phasellus augue neque, laoreet ut dignissim sit amet, tincidunt vel ante. Quisque porttitor ultrices augue et ultricies. Fusce tempus purus diam, nec scelerisque nisl dapibus ac. Sed bibendum gravida euismod. Quisque pretium erat lacus. Integer porta mollis mauris, a elementum turpis rhoncus vel. Aenean consequat ac justo ut tincidunt. In hac habitasse platea dictumst. Phasellus in tempus quam. Duis feugiat, orci in suscipit fringilla, metus massa pellentesque odio, id convallis magna leo nec libero. Morbi blandit dignissim commodo. Duis sed tellus magna. Curabitur non neque quis nunc commodo tincidunt. Nullam neque ligula, mattis sed turpis sit amet, blandit tristique dui. Nulla facilisi. Etiam interdum enim ullamcorper ligula pellentesque luctus. Ut tincidunt elit quis velit convallis, a convallis leo aliquet.",
        image:'https://img.freepik.com/free-vector/breaking-news-concept_23-2148514216.jpg?'
    },
]