export const ActionsTypes = {
    SET_CATEGORY: "SET_CATEGORY",
    SET_SOURCE: "SET_SOURCE",
    ADD_BOOKMARK: "ADD_BOOKMARK",
    DELETE_BOOKMARK: "DELETE_BOOKMARK",
    CLEAR_BOOKMARK: "CLEAR_BOOKMARK"
}